name: Java (8) CI with Maven in Linux 
on:
 push:
 pull_request:
    branches:
        - master

jobs:
 build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8 ]
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          additional-maven-args: >
              -Ppitmutation
              -DrepoToken=$COVERALLS_REPO_TOKEN
              coveralls:report
              -DpullRequest=${{ github.event.pull_request.number }}

    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK  ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
       java-version: ${{ matrix.java }}
    - name: Cache Maven Packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: xvfb-run mvn -f pom.xml clean verify ${{ matrix.additional-maven-args }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    - name: Generate JUnit Report
      run: >
        mvn -f pom.xml
        surefire-report:report-only surefire-report:failsafe-report-only site:site -DgenerateReports=false
      if: ${{ always() }}
    - name: Archive JUnit Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: surefire-report-jdk-${{ matrix.java }}-${{ matrix.os }}
        path: '**/target/site'
    - name: Archive PIT Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: pit-report-files-${{ matrix.java }}-${{ matrix.os }}
        path: '**/target/pit-reports'

